name: Auto Assign to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    name: Assign to "Backlog" Project
    steps:
    - name: Assign NEW issues and NEW pull requests to global project "Backlog" (1)
      uses: actions/add-to-project@main
      with:
        project-url: https://github.com/users/Blackjacx/projects/1
        github-token: ${{ secrets.ACCESS_TOKEN }}